Repository sachiva1/sachiva, pull requests merged in 2025-08, with the labels that each got.

#99 Added Code of Conduct file
  CODE_OF_CONDUCT.md
Labels: documentation, GSSoC25, Level 1

#98 Modified Client Section
  css/style.css
  index.html
Labels: GSSoC25, Level 2

#102 Added Filter Functionality & Fixed UI Alignment in Services and Other Sections
  contributors.html
  css/style.css
  js/service.js
  service.html
Labels: enhancement, GSSoC25, Level 3

#108 Updated About page
  about.html
  css/style.css
Labels: enhancement, GSSoC25, Level 2

#110 Solved overlapping issue
  service.html
Labels: enhancement, GSSoC25, Level 1

#143 Enhanced UI for smart recommender buttons with spacing and hover effect( #140)
  css/dark-mode-fixes.css
  css/style.css
  index.html
Labels: enhancement, GSSoC25, Level 1

#182 Feature: Added Booking Confirmation Page with Summary
  html/booking-confirmation.html
  html/booking.html
Labels: GSSoC25, Level 2
